-- MySQL Script generated by MySQL Workbench
-- Sun Sep 18 20:27:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema periodicals_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema periodicals_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `periodicals_db` DEFAULT CHARACTER SET utf8 ;
USE `periodicals_db` ;

-- -----------------------------------------------------
-- Table `periodicals_db`.`locale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals_db`.`locale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `short_name` VARCHAR(2) NOT NULL,
  `lang_name_original` VARCHAR(45) NOT NULL,
  `currency` VARCHAR(3) NULL DEFAULT 'UAH',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`short_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `periodicals_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `locale_id` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` ENUM('CUSTOMER', 'ADMIN') NULL DEFAULT 'CUSTOMER',
  `balance` INT NULL DEFAULT 0,
  `blocking_status` ENUM('BLOCKED', 'NOT_BLOCKED') NULL DEFAULT 'NOT_BLOCKED',
  PRIMARY KEY (`id`, `locale_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_locale_idx` (`locale_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_locale`
    FOREIGN KEY (`locale_id`)
    REFERENCES `periodicals_db`.`locale` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `periodicals_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals_db`.`address` (
  `user_id` INT NOT NULL,
  `index` INT NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `street` VARCHAR(50) NOT NULL,
  `build` VARCHAR(10) NOT NULL,
  `apartment` VARCHAR(20) NULL DEFAULT 'private house',
  INDEX `fk_addess_user_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_address_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `periodicals_db`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `periodicals_db`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals_db`.`topic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `periodicals_db`.`periodical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals_db`.`periodical` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `topic_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `title_img` VARCHAR(45) NULL DEFAULT 'default_title_img',
  `price_uah` INT NOT NULL,
  `publication_frequency` INT NULL DEFAULT 1,
  `min_subscription_period` INT NULL DEFAULT 1,
  `status` ENUM('ACTIVE', 'DISABLED') NULL DEFAULT 'DISABLED',
  PRIMARY KEY (`id`, `topic_id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  INDEX `fk_periodical_topic_idx` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `fk_periodical_topic`
    FOREIGN KEY (`topic_id`)
    REFERENCES `periodicals_db`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `periodicals_db`.`periodical_translate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals_db`.`periodical_translate` (
  `periodical_id` INT NOT NULL,
  `locale_id` INT NOT NULL,
  `publishing_country` VARCHAR(45) NOT NULL,
  `publishing_lang` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`periodical_id`, `locale_id`),
  INDEX `fk_periodical_translate_periodical_idx` (`periodical_id` ASC) INVISIBLE,
  INDEX `fk_periodical_translate_locale_idx` (`locale_id` ASC) VISIBLE,
  CONSTRAINT `fk_periodical_translate_locale`
    FOREIGN KEY (`locale_id`)
    REFERENCES `periodicals_db`.`locale` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_periodical_translate_periodical`
    FOREIGN KEY (`periodical_id`)
    REFERENCES `periodicals_db`.`periodical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `periodicals_db`.`topic_translate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals_db`.`topic_translate` (
  `topic_id` INT NOT NULL,
  `locale_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`topic_id`, `locale_id`),
  INDEX `fk_topic_translate_topic_idx` (`topic_id` ASC) VISIBLE,
  INDEX `fk_topic_translate_locale_idx` (`locale_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_topic_translate_topic`
    FOREIGN KEY (`topic_id`)
    REFERENCES `periodicals_db`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT ``
    FOREIGN KEY (`locale_id`)
    REFERENCES `periodicals_db`.`locale` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `periodicals_db`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals_db`.`subscription` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `periodical_id` INT NOT NULL,
  `sets_amount` INT NULL DEFAULT 1,
  `total_price_uah` INT NOT NULL,
  `payment_status` ENUM('PAID', 'NOT_PAID') NULL DEFAULT 'NOT_PAID',
  `creation_date` DATE NULL DEFAULT (CURRENT_DATE),
  `status` ENUM('EXPIRED', 'WAITING', 'IN_PROGRESS') NULL DEFAULT 'WAITING',
  PRIMARY KEY (`id`, `user_id`, `periodical_id`),
  INDEX `fk_subscription_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_subscription_periodical_idx` (`periodical_id` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `periodicals_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscription_periodical`
    FOREIGN KEY (`periodical_id`)
    REFERENCES `periodicals_db`.`periodical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `periodicals_db`.`release_month`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals_db`.`release_month` (
  `periodical_id` INT NOT NULL,
  `year` INT NOT NULL,
  `enabled_month` VARCHAR(12) NULL DEFAULT '000000000000',
  PRIMARY KEY (`periodical_id`, `year`),
  INDEX `fk_release_month_periodical_idx` (`periodical_id` ASC) INVISIBLE,
  CONSTRAINT `fk_release_month_periodical`
    FOREIGN KEY (`periodical_id`)
    REFERENCES `periodicals_db`.`periodical` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `periodicals_db`.`subscription_month`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals_db`.`subscription_month` (
  `subscription_id` INT NOT NULL,
  `year` INT NOT NULL,
  `selected_month` VARCHAR(12) NULL DEFAULT '000000000000',
  PRIMARY KEY (`subscription_id`, `year`),
  INDEX `fk_subscription_month_subscription_idx` (`subscription_id` ASC) INVISIBLE,
  CONSTRAINT `fk_subscription_month_subscription`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `periodicals_db`.`subscription` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
